export const cart = [
    {
        roomTempList: [
            {
                productId: 1,
                image: 'https://marketfuby-image.s3.ap-northeast-2.amazonaws.com/1.JPG',
                delivery: '샛별배송',
                bigcategoryId: 1,
                brand: '주칠일',
                title: '관서식 오코노미야끼',
                subtitle: '풍성한 토핑이 콕콕',
                price: 17900,
                discount: 0,
            },
            {
                productId: 2,
                image: 'https://marketfuby-image.s3.ap-northeast-2.amazonaws.com/2.JPG',
                delivery: '샛별배송',
                bigcategoryId: 1,
                brand: '프레시지',
                title: '모닝빵 골라담기',
                subtitle: '안심하고 즐기는 모닝빵',
                price: 11500,
                discount: 7,
            },
            {
                productId: 3,
                image: 'https://marketfuby-image.s3.ap-northeast-2.amazonaws.com/3.JPG',
                delivery: '샛별배송',
                bigcategoryId: 1,
                brand: '야미요밀',
                title: '고기듬뿍 감자탕 2.5kg',
                subtitle: '고기가 듬뿍 들어간',
                price: 6300,
                discount: 10,
            },
        ],
        refrigeList: [
            {
                productId: 4,
                image: 'https://marketfuby-image.s3.ap-northeast-2.amazonaws.com/4.JPG',
                delivery: '판매자배송',
                bigcategoryId: 1,
                brand: '서울리빙',
                title: '고급 올스텐 프리미엄 식기건조대 1단',
                subtitle:
                    '깔끔한 올스텐레스 식기건조대 (수저통+도마거치대 풀구성)',
                price: 69800,
                discount: 57,
            },
            {
                productId: 5,
                image: 'https://marketfuby-image.s3.ap-northeast-2.amazonaws.com/5.JPG',
                delivery: '샛별배송',
                bigcategoryId: 1,
                brand: '비오템',
                title: 'renewal 오 비타미네 바디밀크 점보 400ml 세트 (바디로션)',
                subtitle: '편안한 감촉과 매력적인 잔향',
                price: 69000,
                discount: 15,
            },
            {
                productId: 6,
                image: 'https://marketfuby-image.s3.ap-northeast-2.amazonaws.com/6.JPG',
                delivery: '샛별배송',
                bigcategoryId: 1,
                brand: '웨지우드',
                title: '크리스마스 오너먼트 프레젠트',
                subtitle: null,
                price: 100000,
                discount: 40,
            },
        ],
        frozenList: [
            {
                productId: 7,
                image: 'https://marketfuby-image.s3.ap-northeast-2.amazonaws.com/7.JPG',
                delivery: '샛별배송',
                bigcategoryId: 1,
                brand: '고기반찬',
                title: '양념 소갈비찜 800g',
                subtitle: '달콤짭짤한 양념을 흠뻑 입은',
                price: 34900,
                discount: 0,
            },
            {
                productId: 8,
                image: 'https://marketfuby-image.s3.ap-northeast-2.amazonaws.com/8.JPG',
                delivery: '샛별배송',
                bigcategoryId: 1,
                brand: 'KF365',
                title: '노르웨이 고등어 3종 (택1) (냉동)',
                subtitle: '간편하게 즐기는 고소한 생선',
                price: 6700,
                discount: 0,
            },
        ],
        totalAmount: 10,
        discountAmount: 110,
        paymentAmount: 120,
    },
];
