export const category = [
    {
        title: 'SUPER BIG SALE',
        subtitle: [
            { key: 1, label: '친환경1' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '채소',
        subtitle: [
            { key: 1, label: '친환경2' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '과일·견과쌀',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '수산·해산·건어물',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '정육·계란',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '국·반찬· 메인요리',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '샐러드·간편식',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '면·양념·오일',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '생수·음료·우유·커피',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '간식·과자·떡',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '베이커리·치즈·델리',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '건강식품',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '와인·위스키',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '전통주',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '생활용품·리빙·캠핑',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '스킨케어·메이크업',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '헤어·바디·구강',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
];
