export const category = [
    {
        title: '채소',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '과일·견과쌀',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '국산과일' },
            { key: 3, label: '수입과일' },
            { key: 4, label: '간편과일' },
            { key: 5, label: '냉동 · 건과일' },
            { key: 6, label: '견과류' },
            { key: 7, label: '쌀·잡곡' },
        ],
    },
    {
        title: '수산·해산·건어물',
        subtitle: [
            { key: 1, label: '생선류' },
            { key: 2, label: '제철수산' },
            { key: 3, label: '굴비·반건류' },
            { key: 4, label: '오징어·낙지·문어' },
            { key: 5, label: '해산물·조개류' },
            { key: 6, label: '수산가공품' },
            { key: 7, label: '김·미역·해조류' },
            { key: 8, label: '건어물다시팩' },
        ],
    },
    {
        title: '정육·계란',
        subtitle: [
            { key: 1, label: '국내산 소고기' },
            { key: 2, label: '수입산 소고기' },
            { key: 3, label: '돼지고기' },
            { key: 4, label: '계란류' },
            { key: 5, label: '닭·오리고기' },
            { key: 6, label: '양념육돈까스' },
            { key: 7, label: '양고기' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '국·반찬· 메인요리',
        subtitle: [
            { key: 1, label: '친환경' },
            { key: 2, label: '고구마·감자·당근' },
            { key: 3, label: '시금치·쌈채소·나물' },
            { key: 4, label: '브로콜리·파프리카·양배추' },
            { key: 5, label: '양파·대파·마늘·배추' },
            { key: 6, label: '오이·호박·고추' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '샐러드·간편식',
        subtitle: [
            { key: 1, label: '샐러드·닭가슴살' },
            { key: 2, label: '도시락·밥류' },
            { key: 3, label: '파스타·면류' },
            { key: 4, label: '떡볶이·튀김·순대' },
            { key: 5, label: '피자·핫도그·만두' },
            { key: 6, label: '폭립·떡갈비·안주' },
            { key: 7, label: '죽·스프·카레' },
            { key: 8, label: '선식·시리얼' },
        ],
    },
    {
        title: '면·양념·오일',
        subtitle: [
            { key: 1, label: '파스타·면류' },
            { key: 2, label: '식초·소스·드레싱' },
            { key: 3, label: '양념·액젓·장류' },
            { key: 4, label: '식용유·참기름·오일' },
            { key: 5, label: '소금·설탕·향신료' },
            { key: 6, label: '밀가루가루·믹스' },
        ],
    },
    {
        title: '생수·음료·우유·커피',
        subtitle: [
            { key: 1, label: '생수·탄산수' },
            { key: 2, label: '음료·주스' },
            { key: 3, label: '우유·두유·요거트' },
            { key: 4, label: '커피' },
            { key: 5, label: '차' },
            { key: 6, label: '커피용품' },
        ],
    },
    {
        title: '간식·과자·떡',
        subtitle: [
            { key: 1, label: '과자·스낵·쿠키' },
            { key: 2, label: '초콜릿·젤리·캔디' },
            { key: 3, label: '떡·한과' },
            { key: 4, label: '아이스크림' },
        ],
    },
    {
        title: '베이커리·치즈·델리',
        subtitle: [
            { key: 1, label: '식빵·빵류' },
            { key: 2, label: '잼·버터·스프레드' },
            { key: 3, label: '케이크 ·파이 · 디저트' },
            { key: 4, label: '치즈' },
            { key: 5, label: '델리' },
            { key: 6, label: '올리브·피클' },
            { key: 7, label: '냉동·이색·간편채소' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '건강식품',
        subtitle: [
            { key: 1, label: '영양제' },
            { key: 2, label: '유산균' },
            { key: 3, label: '홍삼·인삼·꿀' },
            { key: 4, label: '건강즙·건강음료' },
            { key: 5, label: '건강분말·건강환' },
            { key: 6, label: '다이어트·이너뷰티' },
            { key: 7, label: '유아동' },
            { key: 8, label: '콩나물·버섯' },
        ],
    },
    {
        title: '와인·위스키',
        subtitle: [
            { key: 1, label: '레드와인' },
            { key: 2, label: '화이트와인' },
            { key: 3, label: '샴페인·스파클링' },
            { key: 4, label: '논알콜' },
            { key: 5, label: '와인·위스키용품' },
        ],
    },
    {
        title: '전통주',
        subtitle: [
            { key: 1, label: '막걸리·탁주' },
            { key: 2, label: '증류주·약주·청주' },
            { key: 3, label: '과실주·리큐르' },
            { key: 4, label: '전통주·선물세트' },
        ],
    },
    {
        title: '생활용품·리빙·캠핑',
        subtitle: [
            { key: 1, label: '휴지.티슈' },
            { key: 2, label: '여성위생용품' },
            { key: 3, label: '세제·청소용품' },
            { key: 4, label: '화훼·인테리어소품' },
            { key: 5, label: '의약외품·마스크' },
            { key: 6, label: '캠핑용품' },
        ],
    },
    {
        title: '스킨케어·메이크업',
        subtitle: [
            { key: 1, label: '스킨·미스트·패드' },
            { key: 2, label: '에센스 앰플 로션' },
            { key: 3, label: '크림·오일' },
            { key: 4, label: '클렌징' },
            { key: 5, label: '마스크팩' },
            { key: 6, label: '선케어' },
            { key: 7, label: '메이크업' },
            { key: 8, label: '맨즈케어' },
            { key: 9, label: '뷰티소품·기기' },
        ],
    },
    {
        title: '헤어·바디·구강',
        subtitle: [
            { key: 1, label: '구강·면도' },
            { key: 2, label: '샴푸·컨디셔너' },
            { key: 3, label: '트리트먼트·팩' },
            { key: 4, label: '헤어에센스·염모' },
            { key: 5, label: '바디워시·스크럽' },
            { key: 6, label: '바디로션·크림' },
            { key: 7, label: '핸드.립·데오' },
            { key: 8, label: '향수·디퓨저' },
            { key: 9, label: '헤어·바디소품' },
        ],
    },
];
