export const FILTER_LIST = [
    { id: 1, label: '간식·과자·떡', clicked: false },
    { id: 2, label: '생활용품·리빙·캠핑', clicked: false },
    { id: 3, label: '베이커리·치즈·델리', clicked: false },
    { id: 4, label: '헤어·바디·구강', clicked: false },
    { id: 5, label: '주방용품', clicked: false },
    { id: 6, label: '생수·음료·우유·커피', clicked: false },
    { id: 7, label: '샐러드·간편식', clicked: false },
    { id: 8, label: '과일·견과·쌀', clicked: false },
    { id: 9, label: '국·반찬·메인요리', clicked: false },
    { id: 10, label: '수산·해산·건어물', clicked: false },
    { id: 11, label: '1주년 기념 뷰티컬리페스타', clicked: false },
    { id: 12, label: '반려동물', clicked: false },
    { id: 13, label: '건강식품', clicked: false },
    { id: 14, label: '베이비·키즈·완구', clicked: false },
    { id: 15, label: '면·양념·오일', clicked: false },
    { id: 16, label: '스킨케어·메이크업', clicked: false },
    { id: 17, label: '정육·계란', clicked: false },
    { id: 18, label: '전통주', clicked: false },
    { id: 19, label: '와인·위스키', clicked: false },
];
